Update selfhosted.yml

diff --git a/.github/workflows/selfhosted.yml b/.github/workflows/selfhosted.yml
--- a/.github/workflows/selfhosted.yml
+++ b/.github/workflows/selfhosted.yml
@@ -1,11 +1,10 @@
-#
 # Copyright (C) 2024-2025 Antonino Scordino
 # Copyright (C) 2024-2025 Souhrud Reddy
 #
 # SPDX-License-Identifier: Apache-2.0
-#
 
 name: Crave Builder(self-hosted)
+
 on:
   workflow_dispatch:
     # Various inputs to simplify usage of workflow.
@@ -28,56 +27,67 @@ on:
           - 'LineageOS 16.0'
           - 'CyanogenMOD 14.1'
           - 'AOSP'
+
       BUILD_DIFFERENT_ROM:
         description: "Command to initialize a different 'repo' project:"
         required: false
         default: "echo 'Build Starting!'"
+
       REMOVALS:
         description: "Folders to be removed before syncing:"
         required: false
+
       LOCAL_MANIFEST:
         description: "Personal local manifest [repository or raw]:"
         required: true
         default: 'https://github.com/sounddrill31/local_manifests_oxygen'
+
       LOCAL_MANIFEST_BRANCH:
         description: "Personal local manifest's branch:"
         required: false
         default: 'lineage-21-qpr3'
+
       DEVICE_NAME:
         description: "Device's codename:"
         required: true
         default: "oxygen"
+
       PRODUCT_NAME:
         description: "Product to build:"
         required: true
         default: "oxygen"
+
       BUILD_COMMAND:
         description: 'Command to be used for compiling:'
         required: true
         default: 'mka bacon'
+
       BUILD_TYPE:
         description: 'Type of build:'
         required: true
         default: 'userdebug'
         type: choice
-        options: 
-        - 'eng'
-        - 'userdebug'
-        - 'user' 
+        options:
+          - 'eng'
+          - 'userdebug'
+          - 'user'
+
       CLEAN_BUILD:
         description: 'Build with a clean workspace?'
         required: true
         default: 'no'
         type: choice
-        options: 
-        - 'yes'
-        - 'no'
+        options:
+          - 'yes'
+          - 'no'
 
 jobs:
+
   Start-Runner:
     runs-on: ubuntu-latest
 
     steps:
+
     - name: Checkout code
       uses: actions/checkout@v4
 
@@ -86,7 +96,7 @@ jobs:
         sudo apt-get update
         sudo apt-get install -y tmux
 
-      # Download and configure 'crave'.
+    # Download and configure 'crave'.
     - name: Configure the 'crave' environment
       run: |
         echo "DCDEVSPACE status: ${DCDEVSPACE}"
@@ -98,11 +108,11 @@ jobs:
           mv ${PWD}/crave ${HOME}/bin/
           sudo ln -sf /home/${USER}/bin/crave /usr/bin/crave
           envsubst < ${PWD}/crave.conf.sample >> ${PWD}/crave.conf
-          rm -rf ${PWD}/crave.conf.sample          
+          rm -rf ${PWD}/crave.conf.sample
         fi
       env:
-        CRAVE_USERNAME: ${{  secrets.CRAVE_USERNAME  }}
-        CRAVE_TOKEN: ${{  secrets.CRAVE_TOKEN  }}
+        CRAVE_USERNAME: ${{ secrets.CRAVE_USERNAME }}
+        CRAVE_TOKEN: ${{ secrets.CRAVE_TOKEN }}
 
     - name: Run crave devspace
       run: |
@@ -115,18 +125,21 @@ jobs:
             exit 1
           fi
 
-        if tmux has-session -t ghactions; then 
-          echo "Runner is already Running" 
-        else 
-          tmux kill-session -t ghactions;
-          tmux new-session -d -s ghactions 
-          tmux send-keys -t ghactions './actions-runner/run.sh' Enter 
-          echo "Runner Started"
-        fi "
+          if tmux has-session -t ghactions; then
+            echo "Runner is already Running"
+          else
+            tmux kill-session -t ghactions;
+            tmux new-session -d -s ghactions
+            tmux send-keys -t ghactions './actions-runner/run.sh' Enter
+            echo "Runner Started"
+          fi "
+
   prepare:
     name: Prepare for Building
     runs-on: ubuntu-latest
+
     steps:
+
     - name: Check-out to repository
       uses: actions/checkout@v4
 
@@ -141,75 +154,89 @@ jobs:
     - name: Set Project variables
       id: proj-variables
       run: |
+
         case "${{ github.event.inputs.BASE_PROJECT }}" in
+
         "ArrowOS 13.1")
           export PROJECTFOLDER="/crave-devspaces/Arrow13"
           export PROJECTID="73"
           export REPO_INIT="repo init -u https://github.com/ArrowOS/android_manifest.git -b arrow-13.1 --depth=1"
         ;;
+
         "DerpFest 14.0")
           export PROJECTFOLDER="/crave-devspaces/DerpFest14"
           export PROJECTID="64"
           export REPO_INIT="repo init -u https://github.com/DerpFest-AOSP/manifest.git -b 14 --depth=1"
         ;;
+
         "LineageOS 21.0")
           export PROJECTFOLDER="/crave-devspaces/Lineage21"
           export PROJECTID="72"
           export REPO_INIT="repo init -u https://github.com/LineageOS/android.git -b lineage-21.0 --git-lfs --depth=1"
         ;;
+
         "LineageOS 22.1")
           export PROJECTFOLDER="/crave-devspaces/Lineage22"
           export PROJECTID="93"
           export REPO_INIT="repo init -u https://github.com/accupara/los22.git -b lineage-22.1 --git-lfs --depth=1"
         ;;
+
         "LineageOS 20.0")
           export PROJECTFOLDER="/crave-devspaces/Lineage20"
           export PROJECTID="36"
           export REPO_INIT="repo init -u https://github.com/accupara/los20.git -b lineage-20.0 --git-lfs --depth=1"
         ;;
+
         "CipherOS 14")
           export PROJECTFOLDER="/crave-devspaces/Cipher14"
           export PROJECTID="79"
           export REPO_INIT="repo init -u https://github.com/CipherOS/android_manifest.git -b fourteen --git-lfs --depth=1"
         ;;
+
         "PixelOS 15")
           export PROJECTFOLDER="/crave-devspaces/Pixel15"
           export PROJECTID="82"
           export REPO_INIT="repo init -u https://github.com/PixelOS-AOSP/manifest.git -b fifteen --git-lfs --depth=1"
         ;;
+
         "RisingOS 15 Revived")
           export PROJECTFOLDER="/crave-devspaces/Rising15"
           export PROJECTID="86"
           export REPO_INIT="repo init -u https://github.com/RisingOS-Revived/android.git -b fifteen --git-lfs --depth=1"
         ;;
+
         "LineageOS 18.1")
           export PROJECTFOLDER="/crave-devspaces/Lineage18"
           export PROJECTID="85"
           export REPO_INIT="repo init -u https://github.com/accupara/los18.git -b lineage-18.1 --git-lfs --depth=1"
         ;;
+
         "LineageOS 16.0")
           export PROJECTFOLDER="/crave-devspaces/Lineage16"
           export PROJECTID="81"
           export REPO_INIT="repo init -u https://github.com/accupara/los16.git -b lineage-16.0 --git-lfs --depth=1"
         ;;
+
         "CyanogenMOD 14.1")
           export PROJECTFOLDER="/crave-devspaces/Cyanogen14"
           export PROJECTID="83"
           export REPO_INIT="repo init -u https://github.com/accupara/los-cm14.1.git -b cm-14.1 --git-lfs --depth=1"
         ;;
+
         "AOSP")
           export PROJECTFOLDER="/crave-devspaces/AOSP"
           export PROJECTID="35"
           export REPO_INIT="repo init -u https://android.googlesource.com/platform/manifest.git -b master --git-lfs --depth=1"
         ;;
+
         esac
 
         if [[ ${{ github.event.inputs.PRODUCT_NAME }} == *_* ]] && [[ ${{ github.event.inputs.PRODUCT_NAME }} != gsi_* ]] && [[ ${{ github.event.inputs.PRODUCT_NAME }} != sdk_* ]] && [[ ${{ github.event.inputs.PRODUCT_NAME }} != *_sprout ]] && [[ ${{ github.event.inputs.PRODUCT_NAME }} != Mi439_* ]] && [[ ${{ github.event.inputs.PRODUCT_NAME }} != Mi8937_* ]]; then
           LUNCH="lunch ${{ github.event.inputs.PRODUCT_NAME }}-${{ github.event.inputs.BUILD_TYPE }}"
         elif [[ "${{ github.event.inputs.BASE_PROJECT }}" == "RisingOS 15 Revived" ]] && [[ "${{ github.event.inputs.BUILD_DIFFERENT_ROM }}" == "echo 'Build Starting!'" ]]; then
-            LUNCH="riseup ${{ github.event.inputs.PRODUCT_NAME }} ${{ github.event.inputs.BUILD_TYPE }}"
+          LUNCH="riseup ${{ github.event.inputs.PRODUCT_NAME }} ${{ github.event.inputs.BUILD_TYPE }}"
         else
-            LUNCH="breakfast ${{ github.event.inputs.PRODUCT_NAME }} ${{ github.event.inputs.BUILD_TYPE }}"
+          LUNCH="breakfast ${{ github.event.inputs.PRODUCT_NAME }} ${{ github.event.inputs.BUILD_TYPE }}"
         fi
 
         if [[ "${{ github.event.inputs.LOCAL_MANIFEST }}" =~ \.xml(/)?$ ]]; then
@@ -222,7 +249,7 @@ jobs:
 
         echo "Building on ${{ github.event.inputs.BASE_PROJECT }} project"
         echo "PROJECTFOLDER=$PROJECTFOLDER" >> "$GITHUB_OUTPUT"
-        echo "PROJECTID=$PROJECTID"  >> "$GITHUB_OUTPUT"
+        echo "PROJECTID=$PROJECTID" >> "$GITHUB_OUTPUT"
         echo "REPO_INIT=$REPO_INIT" >> "$GITHUB_OUTPUT"
         echo "LUNCH=$LUNCH" >> "$GITHUB_ENV"
         echo "LUNCH=$LUNCH" >> "$GITHUB_OUTPUT"
@@ -250,6 +277,7 @@ jobs:
         else
           echo "Displaying is disabled through secrets."
         fi
+
     outputs:
       PROJECTFOLDER: ${{ steps.proj-variables.outputs.PROJECTFOLDER }}
       PROJECTID: ${{ steps.proj-variables.outputs.PROJECTID }}
@@ -261,7 +289,9 @@ jobs:
     name: Test Local Manifests
     needs: prepare
     runs-on: ubuntu-latest
+
     steps:
+
     - name: Set Repo Project
       run: |
         PROJECTFOLDER="${{ needs.prepare.outputs.PROJECTFOLDER }}"
@@ -271,7 +301,7 @@ jobs:
         LOCAL_MANIFEST="${{ needs.prepare.outputs.LOCAL_MANIFEST }}"
 
         echo "PROJECTFOLDER=$PROJECTFOLDER" >> "$GITHUB_ENV"
-        echo "PROJECTID=$PROJECTID"  >> "$GITHUB_ENV"
+        echo "PROJECTID=$PROJECTID" >> "$GITHUB_ENV"
         echo "REPO_INIT=$REPO_INIT" >> "$GITHUB_ENV"
         echo "LUNCH=$LUNCH" >> "$GITHUB_ENV"
         echo "LOCAL_MANIFEST=$LOCAL_MANIFEST" >> "$GITHUB_ENV"
@@ -289,7 +319,7 @@ jobs:
           echo "Repo already installed."
         fi
       continue-on-error: true
-      
+
     - name: Set-up 'git' credential(s)
       run: |
         git config --global user.name "${{ github.actor }}"
@@ -300,19 +330,29 @@ jobs:
       run: |
         rm -rf tester
         mkdir tester
-        cd tester 
+        cd tester
+
         if [ "${{ github.event.inputs.BUILD_DIFFERENT_ROM }}" == "echo 'Build Starting!'" ]; then
           $REPO_INIT
         else
           ${{ github.event.inputs.BUILD_DIFFERENT_ROM }}
-        fi 
+        fi
 
         bash -c "$LOCAL_MANIFEST"
 
-        timeout 1m repo sync --force-sync || { exit_code=$?; [ $exit_code -eq 124 ] || (echo "Error: Process failed with exit code $exit_code"; exit $exit_code); }
+        timeout 1m repo sync --force-sync || {
+          exit_code=$?
+          [ $exit_code -eq 124 ] || (
+            echo "Error: Process failed with exit code $exit_code"
+            exit $exit_code
+          )
+        }
+
         du -csh .
         rm -rf .repo
+
       timeout-minutes: 10
+
     outputs:
       PROJECTFOLDER: ${{ needs.prepare.outputs.PROJECTFOLDER }}
       PROJECTID: ${{ needs.prepare.outputs.PROJECTID }}
@@ -325,9 +365,12 @@ jobs:
     name: Build using foss.crave.io
     needs: test
     runs-on: self-hosted
+
     concurrency:
       group: ${{ github.repository_owner }}
+
     steps:
+
     - name: Set Repo Project
       run: |
         PROJECTFOLDER="${{ needs.test.outputs.PROJECTFOLDER }}"
@@ -337,7 +380,7 @@ jobs:
         LOCAL_MANIFEST="${{ needs.test.outputs.LOCAL_MANIFEST }}"
 
         echo "PROJECTFOLDER=$PROJECTFOLDER" >> "$GITHUB_ENV"
-        echo "PROJECTID=$PROJECTID"  >> "$GITHUB_ENV"
+        echo "PROJECTID=$PROJECTID" >> "$GITHUB_ENV"
         echo "REPO_INIT=$REPO_INIT" >> "$GITHUB_ENV"
         echo "LUNCH=$LUNCH" >> "$GITHUB_ENV"
         echo "LOCAL_MANIFEST=$LOCAL_MANIFEST" >> "$GITHUB_ENV"
@@ -353,8 +396,9 @@ jobs:
           -d text="$message" \
           -d parse_mode="Markdown"
         }
-        
+
         send_telegram_message "Crave Project: ${{ github.event.inputs.BASE_PROJECT }}%0ACrave ProjectID: $PROJECTID %0ABuild for ${{ github.event.inputs.DEVICE_NAME }} has been queued %0ACheck Progress at: %0Ahttps://github.com/$(echo "${{ github.repository }}" | sed 's@_@\\_@g')/actions/runs/${{ github.run_id }}"
+
       env:
         chatId: ${{ secrets.TELEGRAM_TO }}
         botToken: ${{ secrets.TELEGRAM_TOKEN }}
@@ -372,6 +416,7 @@ jobs:
           output=$(source ~/.bashrc 2>&1)
           status=$?
           echo "$output"
+
           if [[ $status -ne 0 ]]; then
             echo "You have a broken .bashrc, please contact a Crave.io Administrator"
             exit 1
@@ -388,6 +433,7 @@ jobs:
     - name: Create Project Folders
       run: |
         echo "DCDEVSPACE status: ${DCDEVSPACE}"
+
         if [[ $DCDEVSPACE != *1* ]]; then
           echo "Symlinking devspace folder"
           mkdir -p devspace
@@ -422,16 +468,18 @@ jobs:
         mkdir -p ${{ github.event.inputs.DEVICE_NAME }}
         cd ${{ github.event.inputs.DEVICE_NAME }}
       continue-on-error: true
-      
+
     - name: Set-up 'git' credential(s)
       run: |
         git config --global user.name "${{ github.actor }}"
         git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
-      
+
     - name: Configure the 'crave' environment
       run: |
         echo "DCDEVSPACE status: ${DCDEVSPACE}"
+
         mkdir -p $PROJECTFOLDER/.repo/manifests
+
         if [[ $DCDEVSPACE == *1* ]]; then
           echo 'Already in devspace'
           if [ -f ~/.crave/crave.conf ]; then
@@ -442,9 +490,10 @@ jobs:
           mv ${PWD}/crave ${HOME}/bin/
           sudo ln -sf /home/${USER}/bin/crave /usr/bin/crave
           envsubst < ${PWD}/crave.conf.sample >> ${PWD}/crave.conf
-          rm -rf ${PWD}/crave.conf.sample       
-          cp crave.conf $PROJECTFOLDER/ 
+          rm -rf ${PWD}/crave.conf.sample
+          cp crave.conf $PROJECTFOLDER/
         fi
+
         if [[ -z "${{ secrets.CUSTOM_YAML }}" ]]; then
           cp configs/crave/crave.yaml.aosp $PROJECTFOLDER/.repo/manifests/crave.yaml
           echo "No Custom Configuration Found, Using Template!"
@@ -453,13 +502,15 @@ jobs:
           echo "${{ secrets.CUSTOM_YAML }}" > $PROJECTFOLDER/.repo/manifests/crave.yaml
           echo "Custom Configuration Found!"
         fi
+
       env:
-        CRAVE_USERNAME: ${{  secrets.CRAVE_USERNAME  }}
-        CRAVE_TOKEN: ${{  secrets.CRAVE_TOKEN  }}
+        CRAVE_USERNAME: ${{ secrets.CRAVE_USERNAME }}
+        CRAVE_TOKEN: ${{ secrets.CRAVE_TOKEN }}
 
     - name: Set the 'crave' project
       run: |
         cd $PROJECTFOLDER
+
         if grep -q "$PROJECTFOLDER" <(crave clone list --json | jq -r '.clones[]."Cloned At"') || [[ "${DCDEVSPACE}" == "1" ]]; then
           echo "Using Crave Clone... skipping"
         else
@@ -474,6 +525,7 @@ jobs:
           export BUILD_DIFFERENT_ROM="${{ github.event.inputs.BUILD_DIFFERENT_ROM }}"
           echo "Building $BUILD_DIFFERENT_ROM"
         fi
+
         echo "BUILD_DIFFERENT_ROM=$BUILD_DIFFERENT_ROM" >> "$GITHUB_ENV"
         echo "We will be building with $LUNCH"
 
@@ -481,18 +533,18 @@ jobs:
       if: ${{ github.event.inputs.BUILD_DIFFERENT_ROM != 'skip' }}
       run: |
         cd $PROJECTFOLDER
-        
+
         if [ ! -f crave.conf ] && [ -f ~/.crave/crave.conf ]; then
           cp ~/.crave/crave.conf ./crave.conf
         fi
 
         if [ "${{ github.event.inputs.CLEAN_BUILD }}" == "yes" ]; then
-           export CLEAN="--clean"
+          export CLEAN="--clean"
         fi
 
         if [[ -n "${{ secrets.PAID }}" ]]; then
-           echo "Paid Build... Tokens will be consumed."
-           export PAID="--platform aosp-silver"
+          echo "Paid Build... Tokens will be consumed."
+          export PAID="--platform aosp-silver"
         fi
 
         echo "Build is queued! Starting build run..."
@@ -500,27 +552,25 @@ jobs:
         crave ${{ secrets.CRAVE_FLAGS }} run --no-patch ${PAID} ${CLEAN} -- "rm -rf .repo/local_manifests/ ${{ github.event.inputs.REMOVALS }} && \
         $BUILD_DIFFERENT_ROM ; \
         $LOCAL_MANIFEST && \
-
         if [ -f /usr/bin/resync ]; then
           /usr/bin/resync
         else
           /opt/crave/resync.sh
         fi && \
-
         export BUILD_USERNAME=${{ github.actor }} ; \
         export BUILD_HOSTNAME=crave ; \
         (cd device/xiaomi/sky && git fetch origin && git reset --hard origin/15.0) || true ; \
         rm -rf hardware/xiaomi/aidl/sensors device/xiaomi/sky/gps hardware/qcom-caf/sm8450/audio/agm/service hardware/qcom-caf/sm8450/audio/agm/ipc/HwBinders/agm_ipc_service out/soong/Android-lineage_sky.mk ; \
+        sed -i '/hardware\/qcom-caf\/sm8450\",/a\        \"hardware/qcom-caf/sm8450/audio/agm/ipc/HwBinders/interfaces/AGMIPC/1.0\",' vendor/xiaomi/sky/Android.bp ; \
         source build/envsetup.sh && \
-
         echo "Repository: ${{ github.repository }}"; \
         echo "Run ID: ${{ github.run_id }}"; \
-
         $LUNCH && ${{ github.event.inputs.BUILD_COMMAND }}"
+
       timeout-minutes: 1440
 
     - name: Telegram Notification
-      if:  ${{ success() }}
+      if: ${{ success() }}
       continue-on-error: true
       run: |
         send_telegram_message() {
@@ -541,7 +591,7 @@ jobs:
         skipSuccess: false
 
     - name: Telegram Notification
-      if:  ${{ cancelled() || failure() }}
+      if: ${{ cancelled() || failure() }}
       continue-on-error: true
       run: |
         send_telegram_message() {
@@ -560,6 +610,7 @@ jobs:
         fi
 
         send_telegram_message "Crave Project: ${{ github.event.inputs.BASE_PROJECT }}%0ACrave ProjectID: $PROJECTID %0ABuild for ${{ github.event.inputs.DEVICE_NAME }} $jobMessage %0ACheck Progress at: %0Ahttps://github.com/$(echo "${{ github.repository }}" | sed 's@_@\\_@g')/actions/runs/${{ github.run_id }}"
+
       env:
         chatId: ${{ secrets.TELEGRAM_TO }}
         botToken: ${{ secrets.TELEGRAM_TOKEN }}
@@ -576,8 +627,10 @@ jobs:
       run: |
         cd $PROJECTFOLDER
         echo "${{ secrets.GITHUB_TOKEN }}" > token.txt
+
         crave push token.txt -d $(crave ssh -- pwd | grep -v Select | sed -s 's/\r//g')/
-        crave ssh -- "export GH_UPLOAD_LIMIT="${{ secrets.GH_UPLOAD_LIMIT }}"; bash /opt/crave/github-actions/upload.sh '${{ github.run_id }}' '${{ github.event.inputs.DEVICE_NAME }}'  '${{ github.repository }}' '${{ github.event.inputs.PRODUCT_NAME }}-${{ github.run_id }}' '${{ secrets.EXTRA_FILES }}'"
+
+        crave ssh -- "export GH_UPLOAD_LIMIT="${{ secrets.GH_UPLOAD_LIMIT }}"; bash /opt/crave/github-actions/upload.sh '${{ github.run_id }}' '${{ github.event.inputs.DEVICE_NAME }}' '${{ github.repository }}' '${{ github.event.inputs.PRODUCT_NAME }}-${{ github.run_id }}' '${{ secrets.EXTRA_FILES }}'"
 
     - name: Display error.log
       if: ${{ failure() }}
