Update default project settings in selfhosted.yml

diff --git a/.github/workflows/selfhosted.yml b/.github/workflows/selfhosted.yml
--- a/.github/workflows/selfhosted.yml
+++ b/.github/workflows/selfhosted.yml
@@ -11,9 +11,10 @@ on:
       BASE_PROJECT:
         description: 'Choose a base project:'
         required: true
-        default: 'crDroid 15.0'
+        default: 'LineageOS 24.0'
         type: choice
         options:
+          - 'LineageOS 24.0'
           - 'crDroid 15.0'
           - 'LineageOS 20.0'
           - 'LineageOS 21.0'
@@ -40,12 +41,12 @@ on:
       LOCAL_MANIFEST:
         description: "Personal local manifest [repository or raw]:"
         required: true
-        default: 'https://github.com/sounddrill31/local_manifests_oxygen'
+        default: 'https://github.com/Yadu72485/local_manifests_sky'
 
       LOCAL_MANIFEST_BRANCH:
         description: "Personal local manifest's branch:"
         required: false
-        default: 'lineage-21-qpr3'
+        default: 'main'
 
       DEVICE_NAME:
         description: "Device's codename:"
@@ -55,7 +56,7 @@ on:
       PRODUCT_NAME:
         description: "Product to build:"
         required: true
-        default: "lineage_sky"
+        default: "sky"
 
       BUILD_COMMAND:
         description: 'Command to be used for compiling:'
@@ -155,6 +156,12 @@ jobs:
 
         case "${{ github.event.inputs.BASE_PROJECT }}" in
         
+        "LineageOS 24.0")
+          export PROJECTFOLDER="/crave-devspaces/Lineage24"
+          export PROJECTID="93"
+          export REPO_INIT="repo init -u https://github.com/LineageOS/android.git -b lineage-24.0 --git-lfs --depth=1"
+        ;;
+
         "crDroid 15.0")
           export PROJECTFOLDER="/crave-devspaces/crDroid15"
           export PROJECTID="93"
@@ -482,7 +489,7 @@ jobs:
       run: |
         echo "DCDEVSPACE status: ${DCDEVSPACE}"
 
-        mkdir -p $PROJECTFOLDER/.repo/manifests
+        mkdir -p $PROJECTFOLDER/.repo/manifests ${HOME}/.crave/
 
         if [[ $DCDEVSPACE == *1* ]]; then
           echo 'Already in devspace'
@@ -493,9 +500,14 @@ jobs:
           curl -s https://raw.githubusercontent.com/accupara/crave/master/get_crave.sh | bash -s --
           mv ${PWD}/crave ${HOME}/bin/
           sudo ln -sf /home/${USER}/bin/crave /usr/bin/crave
-          envsubst < ${PWD}/crave.conf.sample >> ${PWD}/crave.conf
-          rm -rf ${PWD}/crave.conf.sample
-          cp crave.conf $PROJECTFOLDER/
+          
+          if [ -f ${PWD}/crave.conf ]; then
+            cp ${PWD}/crave.conf ${HOME}/.crave/crave.conf
+            cp ${PWD}/crave.conf $PROJECTFOLDER/crave.conf || true
+          else
+            echo "Error: crave.conf not found!"
+            exit 1
+          fi
         fi
 
         if [[ -z "${{ secrets.CUSTOM_YAML }}" ]]; then
@@ -561,7 +573,7 @@ jobs:
         else
           /opt/crave/resync.sh
         fi && \
-        sudo apt-get update && sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git git-lfs gnupg gperf imagemagick lib32ncurses-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses6 libncurses-dev libsdl1.2-dev libssl-dev libwxgtk3.2-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev && \
+        sudo apt-get update && sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git git-lfs gnupg gperf imagemagick lib32ncurses-dev lib32readline-dev lib32z1-dev lz4 libncurses6 libncurses-dev libsdl1.2-dev libssl-dev libwxgtk3.2-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev && \
         export BUILD_USERNAME=${{ github.actor }} ; \
         export BUILD_HOSTNAME=crave ; \
         export USE_CCACHE=1 ; \
